name: Build

on:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  PROJECT_PATH: src/TwitchOverlayHelper/TwitchOverlayHelper.csproj

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        shell: pwsh
        run: dotnet restore $env:PROJECT_PATH

      - name: Build app
        shell: pwsh
        run: dotnet build $env:PROJECT_PATH -c Release --no-restore
